#!/bin/sh
# postrm script for grid
set -e

case "$1" in
    purge)
        rm -rf /var/lib/grid
        deluser --quiet --system grid 2>/dev/null || true
        delgroup --quiet --system grid 2>/dev/null || true
        rm -f /etc/default/grid
        ;;
esac

#DEBHELPER#
exit 0
