services:
  rustkan:
    image: ubermetroid/rustkan:latest
    build: .
    container_name: rustkan
    restart: unless-stopped
    ports:
      - ${PORT:-4405}:4405
    environment:
      - SITE_TITLE=${SITE_TITLE:-RustKan}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - RUSTKAN_PIN=${RUSTKAN_PIN}
    volumes:
      - ./data:/usr/src/app/data
