name: "Build & Test (CI)"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - name: Install Trunk
        run: |
          wget -qO- "https://github.com/trunk-rs/trunk/releases/download/v0.21.14/trunk-x86_64-unknown-linux-gnu.tar.gz" | tar -xzf- -C /usr/local/bin

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Check backend clippy lints
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run unit tests
        run: cargo test --workspace

      - name: Build WebAssembly Frontend (Trunk)
        run: |
          cd frontend
          trunk build --release
